### ISSUE TITLE
what is the status of this project?

### ISSUE THREAD

**Issue by assem-ch** [LBenzahia/alfanous_mobile_interfaces#11]

**Comment by greenat92** [comment]
Outstanding, Please can i invite you as a owner  to work on it or find someone else to work on ?

**Comment by assem-ch** [comment]
@LBenzahia what's its progress?

**Comment by LBenzahia** [comment]
Yes

**Comment by assem-ch** [comment]
I mean is it linked already to alfanous api with basic search functionality?

**Comment by greenat92** [comment]
No not yet, I have added sample data, and project structure .
